site_name: Mathlingua
theme:
  name: material
  palette:
    - scheme: default
      primary: blue
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Introduction: index.md
  - Getting Started: getting_started.md
  - Overview: overview.md
  - Mathlore: mathlore.md
  - The Prototype: prototype/index.html
  - About the Author: author.md
  - Source Code: source.md
  - Contact: contact.md
